<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9723f64e-3799-4080-ba1c-bcdd2498088b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="AspNet.Security.OAuth.GitHub" Version="8.3.0" />
    <PackageReference Include="Google.Apis.Auth.AspNetCore3" Version="1.75.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.28" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="8.0.28" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PharmacyApplication\Pharmacy.Application.csproj" />
    <ProjectReference Include="..\PharmacyInfrastructure\Pharmacy.Infrastructure.csproj" />
  </ItemGroup>

</Project>
